name = "JACC"
uuid = "0979c8fe-16a4-4796-9b82-89a9f10403ea"
authors = ["pedrovalerolara <valerolarap@ornl.com>", "williamfgc <williamfgc@yahoo.com>"]
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
